### PR TITLE
Add support for stats adjacent to status bar

### PR DESCRIPTION
**Pull request by scar45**
Hey there! Awesome work on this very customizable mod.

I am an ultrawide user, so I prefer the centered Status Bar, however there was no option to have the stats adjacent to it, and I found it cumbersome to have them on the extreme edge of the viewport. I've never tinkered with zScript before, but the project code is clean, and well commented, so I gave it a shot, surprisingly made good headway, and put it through QA paces. Everything works quite well, using any supplied font. I have some switch cases in order to handle the fonts, due to their different metrics/sizing, as I was careful to ensure there was no overlapping/justification issues/etc..

The code in this PR will tell all, and you will notice some hardcoded values, however I believe they would be consistent across all viewports, since the very bottom edge is used for vertical placement, and the horizontal placement is based on the center-point of the Status Bar, with a (+/-) offset. Since the (non-split) Status Bar should be a consistent size, changing resolution/etc., doesn't seem to break anything.

Here's a quick preview of (most, if not all?) permutations/combinations of the settings:

https://user-images.githubusercontent.com/262645/208263441-6523a3d7-7cdc-4ef9-9457-3f2ea00fb571.mp4

Please inspect the code, test it out, and if everything looks good, I would be gracious if it  was merged in.

P.S. - Sorry for the large diff, but my editor removed whitespace, and changed line endings. The bulk of significant changes start at `L412` in `zscript/stats/stats.zs`, where the rest are mainly string and menu option updates. 

Thanks in advance!

### CODE REVIEW

**Comment by NightFright2k19** [comment]
What happens if you are using a widescreen statusbar (even though you shouldn't mix this mod with such enhancements) and there's not enough space left on either side to show those stats? It can also happen when scaling up the statusbar. Will the text clip into the graphics or automatically jump on top (like with our previous bottom-aligned option)? That would be ideal.

But well... one would assume that nobody that wants the stats on both sides would create conditions that make usage impossible. But then again, user-sided mistakes like this one must be taken into consideration.

Besides that, I'd prefer to not have yet another variable introduced, but rather implement this as another option as part of the alignment set, the top/center/bottom section. Also because if you choose this, the other alignments don't really make much sense, tbh (at least anything with top/center).

**Comment by scar45** [comment]
Good points, and I've tried to test as much as I can but as you mentioned, when you start mixing mods, all sorts of funky results may happen. Here's a quick test when I tried using your nice `doom_wide.wad` mod, _loaded either before, or after_:

`fullscrn_huds` WITH my modification:
Screenshot_Doom_20221217_173552

`fullscrn_huds` WITHOUT my modification:
Screenshot_Doom_20221217_173627

It looks like a separate issue which is causing the wide status bar to be 'squished' into the original space when both `doom_wide.wad` and `fullscrn_huds` are used together. Also, I tried scaling the bar, and it scales perfectly (here's an example of the highest, look at the weapon to see scaling is indeed enabled):

Screenshot_Doom_20221217_174752

With regards to my mod, in every test case I attempted, the text did not clip into any graphics. Well, it did when I started, but that's why I wrote more conditions to account for the different fonts, and nothing collides now.

I can understand that a new var may not be best, since the new option I created only applies when choosing "Bottom left" or "Bottom right". I can try to refactor it all to add 2 new alignment options, maybe "Left/Right of Status Bar", and that would eliminate the need for an extra CVAR and menu options. I'll give that a shot and update this PR when I get a chance.

Thanks for the feedback!

**Comment by scar45** [comment]
Thanks again for the feedback @NightFright2k19. I put much more time and thought (and testing) into this next version, and I believe it is solid. Here's the main list of what I was able to improve:

- Remove CVar and add 2 new positioning options instead
  - This removes the original "Adjacent to Status Bar" CVar, and instead offers two new positioning options of "Status Bar (Left/Right)" 
- Support Split Bar
  - The stats will reposition themselves based on whether or not Split Bar is active 
- Support Heretic/Hexen/Freedoom
  - There is a slight offset added for Heretic/Hexen, as their status bars differ in size from Doom
  - Hexen: Stats now reposition if the player has an inventory item, or they (temporarily) disappear) if browsing the inventory

Here's a quick sample video capture of many configurations:

https://user-images.githubusercontent.com/262645/208491591-79ef6a25-7eee-4903-92fc-50b13ff7ecc9.mp4

...and here's an example of the Hexen workaround that is in place (note the right side, and how stats disappear when browsing inventory, so as to not overlap):

https://user-images.githubusercontent.com/262645/208491684-a69932a3-7ea7-41bd-a77b-4825be455545.mp4

Finally, here is a build based on this latest commit, which I'm hoping you may be able to test:
### > [fullscrn_huds_ef38b33.zip](https://github.com/3saster/fullscrn_huds/files/10261667/fullscrn_huds_ef38b33.zip) (346.6 kb)
_(renamed .pk3 to .zip because GitHub)_
 
I'll standby for any additional feedback, or perhaps a merge approval. Cheers, and thanks again for your consideration.

**Comment by NightFright2k19** [comment]
I'll be honest, I am pretty preoccupied with my projects for the Duke4 community ATM and I don't realistically see myself taking a look at this before early next year. (Plus I won't be around for the next 14d due to my vacation abroad, anyway.) Also, I'd like 3saster to take a look at this as well since he is far more into ZScript than me. Unfortunately, he hasn't been around for a while and I am not sure when he'll be back.

That being said, the feature looks promising in its current state, even though it's yet another level stats-related enhancement, which is actually rather a side feature of the mod and we are focussing far too much on it for my taste. (But well, I guess it's a sign that we are mostly done with the statusbar-related features.) It might take a bit before this can find its way into the master branch, but I am pretty sure that it will.

**Comment by scar45** [comment]
Not a problem at all! I am certainly in no hurry.

I agree that the mod is near-complete, and I think this minor addition would provide a great benefit, mainly to other ultrawide users. I've found that my eyes need to travel much more when stats/etc., are anchored to the left/right edges of the screen, rather than a quick condensed glance down at the middle.

I must thank you again @NightFright2k19 for the feedback because it led me to learn even more, and greatly improve over my first attempt. Hopefully @3saster will take a look one day, and possibly agree that it would be fit for inclusion.

Enjoy your vacation, cheers!

**Review by NightFright2k19 — APPROVED** [review]
After a long time, I've come to the conclusion that this feature is better than none at all after two years without anything. Plus it seems sophisticated enough.

**Pull request merged**
